# Generated by Django 5.2.7 on 2025-12-04 01:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Логин')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль')),
                ('master_code', models.CharField(choices=[('alexander', 'Александр Петров'), ('mikhail', 'Михаил Козлов'), ('dmitry', 'Дмитрий Соколов'), ('admin', 'Администратор')], max_length=20, verbose_name='Код мастера')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Аккаунт мастера',
                'verbose_name_plural': 'Аккаунты мастеров',
            },
        ),
        migrations.CreateModel(
            name='StyleConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Имя может содержать только буквы, пробелы и дефисы', regex='^[А-Яа-яЁёA-Za-z\\s\\-]+$')], verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона. Пример: +7(900)123-45-67 или 89001234567', regex='^(\\+7|8)[\\-\\s]?\\(?\\d{3}\\)?[\\-\\s]?\\d{3}[\\-\\s]?\\d{2}[\\-\\s]?\\d{2}$')], verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator(message='Введите корректный email адрес')], verbose_name='Email')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(12, message='Минимальный возраст - 12 лет'), django.core.validators.MaxValueValidator(100, message='Максимальный возраст - 100 лет')], verbose_name='Возраст')),
                ('hair_type', models.CharField(choices=[('straight', 'Прямые'), ('wavy', 'Волнистые'), ('curly', 'Кудрявые'), ('thin', 'Тонкие'), ('thick', 'Густые')], max_length=50, verbose_name='Тип волос')),
                ('face_shape', models.CharField(choices=[('oval', 'Овальное'), ('round', 'Круглое'), ('square', 'Квадратное'), ('heart', 'Сердцевидное'), ('diamond', 'Ромбовидное')], max_length=50, verbose_name='Форма лица')),
                ('current_style', models.TextField(help_text='Опишите вашу текущую прическу', verbose_name='Текущая стрижка')),
                ('desired_style', models.TextField(help_text='Какую стрижку вы хотите?', verbose_name='Желаемый образ')),
                ('preferences', models.TextField(blank=True, help_text='Что вам нравится/не нравится в стрижках?', verbose_name='Предпочтения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Консультация по стилю',
                'verbose_name_plural': 'Консультации по стилю',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Неверный формат телефона', regex='^\\+?[78]\\d{10}$')], verbose_name='Телефон')),
                ('master', models.CharField(choices=[('alexander', 'Александр Петров'), ('mikhail', 'Михаил Козлов'), ('dmitry', 'Дмитрий Соколов')], max_length=20, verbose_name='Мастер')),
                ('service', models.CharField(choices=[('male_haircut', 'Мужская стрижка'), ('machine_haircut', 'Стрижка машинкой'), ('model_haircut', 'Модельная стрижка'), ('styling', 'Укладка и стайлинг'), ('beard_trim', 'Стрижка бороды'), ('royal_shave', 'Королевское бритье'), ('beard_complex', 'Комплекс "Борода+"'), ('gray_camouflage', 'Камуфляж седины')], max_length=50, verbose_name='Услуга')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'unique_together': {('master', 'date', 'time')},
            },
        ),
    ]
