# Generated by Django 5.2.7 on 2025-11-05 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Неверный формат телефона', regex='^\\+?[78]\\d{10}$')], verbose_name='Телефон')),
                ('master', models.CharField(choices=[('alexander', 'Александр Петров'), ('mikhail', 'Михаил Козлов'), ('dmitry', 'Дмитрий Соколов')], max_length=20, verbose_name='Мастер')),
                ('service', models.CharField(choices=[('male_haircut', 'Мужская стрижка'), ('machine_haircut', 'Стрижка машинкой'), ('model_haircut', 'Модельная стрижка'), ('styling', 'Укладка и стайлинг'), ('beard_trim', 'Стрижка бороды'), ('royal_shave', 'Королевское бритье'), ('beard_complex', 'Комплекс "Борода+"'), ('gray_camouflage', 'Камуфляж седины')], max_length=50, verbose_name='Услуга')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'unique_together': {('master', 'date', 'time')},
            },
        ),
    ]
