# Generated by Django 5.2.7 on 2025-12-02 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Логин')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль')),
                ('master_code', models.CharField(choices=[('alexander', 'Александр Петров'), ('mikhail', 'Михаил Козлов'), ('dmitry', 'Дмитрий Соколов')], max_length=20, unique=True, verbose_name='Код мастера')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Аккаунт мастера',
                'verbose_name_plural': 'Аккаунты мастеров',
            },
        ),
    ]
