# Generated by Django 5.2.7 on 2025-12-02 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_masteraccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masteraccount',
            name='master_code',
            field=models.CharField(choices=[('alexander', 'Александр Петров'), ('mikhail', 'Михаил Козлов'), ('dmitry', 'Дмитрий Соколов'), ('admin', 'Администратор')], max_length=20, verbose_name='Код мастера'),
        ),
    ]
