# Generated by Django 5.2.7 on 2025-12-05 00:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_booking_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Ваше имя')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона', regex='^(\\+7|8)[\\-\\s]?\\(?\\d{3}\\)?[\\-\\s]?\\d{3}[\\-\\s]?\\d{2}[\\-\\s]?\\d{2}$')], verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('visit_date', models.DateField(blank=True, null=True, verbose_name='Дата посещения')),
                ('cleanliness_rating', models.IntegerField(choices=[(1, '1 - Очень плохо'), (2, '2 - Плохо'), (3, '3 - Удовлетворительно'), (4, '4 - Хорошо'), (5, '5 - Отлично')], default=3, verbose_name='Чистота в салоне')),
                ('staff_friendliness', models.IntegerField(choices=[(1, '1 - Очень плохо'), (2, '2 - Плохо'), (3, '3 - Удовлетворительно'), (4, '4 - Хорошо'), (5, '5 - Отлично')], default=3, verbose_name='Вежливость персонала')),
                ('master_skill', models.IntegerField(choices=[(1, '1 - Очень плохо'), (2, '2 - Плохо'), (3, '3 - Удовлетворительно'), (4, '4 - Хорошо'), (5, '5 - Отлично')], default=3, verbose_name='Профессионализм мастера')),
                ('service_speed', models.IntegerField(choices=[(1, '1 - Очень плохо'), (2, '2 - Плохо'), (3, '3 - Удовлетворительно'), (4, '4 - Хорошо'), (5, '5 - Отлично')], default=3, verbose_name='Скорость обслуживания')),
                ('price_quality', models.IntegerField(choices=[(1, '1 - Очень плохо'), (2, '2 - Плохо'), (3, '3 - Удовлетворительно'), (4, '4 - Хорошо'), (5, '5 - Отлично')], default=3, verbose_name='Соотношение цены и качества')),
                ('waiting_time', models.IntegerField(default=0, verbose_name='Время ожидания (минут)')),
                ('master_choice', models.CharField(blank=True, choices=[('alexander', 'Александр Петров'), ('mikhail', 'Михаил Козлов'), ('dmitry', 'Дмитрий Соколов')], max_length=20, verbose_name='Какого мастера вы посещали?')),
                ('service_type', models.CharField(blank=True, choices=[('male_haircut', 'Мужская стрижка'), ('machine_haircut', 'Стрижка машинкой'), ('model_haircut', 'Модельная стрижка'), ('styling', 'Укладка и стайлинг'), ('beard_trim', 'Стрижка бороды'), ('royal_shave', 'Королевское бритье'), ('beard_complex', 'Комплекс "Борода+"'), ('gray_camouflage', 'Камуфляж седины')], max_length=50, verbose_name='Какую услугу вы получали?')),
                ('would_recommend', models.BooleanField(default=True, verbose_name='Порекомендуете ли вы нас друзьям?')),
                ('improvements', models.TextField(blank=True, help_text='Ваши предложения по улучшению нашего сервиса', verbose_name='Что мы можем улучшить?')),
                ('other_comments', models.TextField(blank=True, verbose_name='Дополнительные комментарии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заполнения')),
            ],
            options={
                'verbose_name': 'Отзыв о качестве',
                'verbose_name_plural': 'Отзывы о качестве',
                'ordering': ['-created_at'],
            },
        ),
    ]
