# Generated by Django 5.2.7 on 2025-12-03 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_masteraccount_master_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='StyleConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('hair_type', models.CharField(choices=[('straight', 'Прямые'), ('wavy', 'Волнистые'), ('curly', 'Кудрявые'), ('thin', 'Тонкие'), ('thick', 'Густые')], max_length=50, verbose_name='Тип волос')),
                ('face_shape', models.CharField(choices=[('oval', 'Овальное'), ('round', 'Круглое'), ('square', 'Квадратное'), ('heart', 'Сердцевидное'), ('diamond', 'Ромбовидное')], max_length=50, verbose_name='Форма лица')),
                ('current_style', models.TextField(help_text='Опишите вашу текущую прическу', verbose_name='Текущая стрижка')),
                ('desired_style', models.TextField(help_text='Какую стрижку вы хотите?', verbose_name='Желаемый образ')),
                ('preferences', models.TextField(blank=True, help_text='Что вам нравится/не нравится в стрижках?', verbose_name='Предпочтения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Консультация по стилю',
                'verbose_name_plural': 'Консультации по стилю',
                'ordering': ['-created_at'],
            },
        ),
    ]
