# Generated by Django 5.2.7 on 2025-11-17 23:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+79999999999'. До 15 цифр.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Номер телефона')),
                ('master', models.CharField(max_length=100, verbose_name='Мастер')),
                ('service', models.CharField(max_length=100, verbose_name='Услуга')),
                ('date', models.DateField(verbose_name='Дата записи')),
                ('time', models.TimeField(verbose_name='Время записи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='review',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Проверен (клиент подтвержден)'),
        ),
        migrations.AddField(
            model_name='review',
            name='phone',
            field=models.CharField(default=70000000000, help_text='Введите номер, который использовали при записи', max_length=17, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+79999999999'. До 15 цифр.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
