# Generated by Django 5.2.7 on 2025-11-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_booking_review_is_verified_review_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.AlterField(
            model_name='review',
            name='phone',
            field=models.CharField(help_text='Введите номер, который использовали при записи', max_length=20, verbose_name='Номер телефона'),
        ),
    ]
